name: Build

on: [workflow_dispatch, push]

jobs:
  build:
    name: Build iOS
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true

      - run: |
          sudo gem install u3d
          sudo u3d install 2019.1.0f2 -p Unity,iOS

      - run: |
          git clone --depth=1 https://gitlab+deploy-token-383357:9qK9eTgVopu4Luwcn4xk@gitlab.com/kabbouchi/soft-dev-inc.git .
      
      - run: |
          u3d -u 2019.1.0f2 -- -batchmode -nographics -quit -silent-crashes -logFile editor.log -username ${{ secrets.UNITY_USERNAME }} -password ${{ secrets.UNITY_PASSWORD }} -serial ${{ secrets.UNITY_SERIAL }} -buildTarget iOS -executeMethod UnityBuild.BatchBuild.Build -outputPath "Output"
      - run: |
          ls
          ls Output
